version: "3"

services:
  api:
    container_name: api
    build: .
    command: yarn test
    ports:
      - "3000:80"
    volumes:
      - .:/usr/api
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
